### ISSUE TITLE
Player is occasionally not spawned

### ISSUE THREAD

**Issue by kyle-sammons** [Jvargasw/CIS410FightingMongooses#10]
The player character is currently not instantiated on occasion. I'm not sure why this is, but it's a known bug that I'm working to fix.

**Comment by Jvargasw** [comment]
[BugVideo1.zip](https://github.com/Jvargasw/CIS410FightingMongooses/files/263484/BugVideo1.zip)

On a related note, now there is also a bug where only one player spawns (might be that they spawn on the same square). This allows you to move once before the game freezes. (See attached)

**Comment by kyle-sammons** [comment]
Fixed. (hopefully)
