### ISSUE TITLE
Occasional loss of control of second player after turn

### ISSUE THREAD

**Issue by Jvargasw** [Jvargasw/CIS410FightingMongooses#17]
Repeated instances of turns where if I end my turn on one player, I lose control of the other. This either ends in re-gaining control (if I can manage to kill an enemy) or after a few turns the enemy basically absorbing the player that lost control and control being lost for the only player left.

Instances where it has happened to me:
- After a turn with all movement and no attack
  -When I end the turn selected on the secondary player

**Comment by TurloThompson** [comment]
An important thing to note is you might have just not ended the inactive players turn. It likely is still treating that player as having used all its movement, making you hit enter again before you can control it. Making this a terrible feature, but not a bug. Reworking the turn system for beta and adding in an indicator for remaining movement of a piece would likely fix this.
