### ISSUE TITLE
Fog of War Positioning

### ISSUE THREAD

**Issue by ryeleo** [Jvargasw/CIS410FightingMongooses#26]
Fix for Fog of War positioning based on discussion during Office Hours.

`  
GameObject instance = (GameObject)Instantiate(fogOWar, new Vector3(room.x + room.width/2, room.y + room.height/2, -1.0f), Quaternion.Euler(-90, 0, 0));
                instance.transform.localScale = new Vector3(0.1f \* (room.width + 2), 1, 0.1f \* (room.height + 2));

`

**Comment by kyle-sammons** [comment]
Thanks Ryan!
