### ISSUE TITLE
Optimize generation by generating room quads, rather than cubes

### ISSUE THREAD

**Issue by kyle-sammons** [Jvargasw/CIS410FightingMongooses#3]
Currently we generate a cube on each section of the walkable terrain in a room. However, we could greatly optimize memory/CPU usage by just creating a single quad for the room floor, rather than generating cubes for each section of it.

**Comment by ryeleo** [comment]
The work solution that we cane to during office hours.

`GameObject instance = (GameObject)Instantiate(walkablePrefab, new Vector3((map.renderHeight1)/2.0f, (map.renderWidth-1)/2.0f, 1.0f), Quaternion.Euler(-90, 0, 0));
instance.transform.localScale = new Vector3(0.1f*map.renderHeight, 1, 0.1f*map.renderWidth);
`
