### ISSUE TITLE
Player can still move behind pause menu/ death screen.

### ISSUE THREAD

**Issue by Jvargasw** [Jvargasw/CIS410FightingMongooses#39]
Player objects can still take input while paused or dead. Confirmed by Turlo to be both the pause menu and the death screen. timescale = 0 may not work for our game due to the way movement/turns are implemented. Ideas?

**Comment by kyle-sammons** [comment]
Just send out a message to all objects to pause. Have each script implement an "OnPause()" function that sets "paused = true", then surround the Update code with "if(!paused) { ... }". That's how we've done it in every other game.
